### ISSUE TITLE
Tag 0.5.1 release in GitHub

### ISSUE THREAD

**Issue by plantfansam** [tom-dalton-fanduel/fdjangodog#14]
Hi! Pypi [shows an 0.5.1 release](https://pypi.python.org/pypi/fdjangodog/0.5.1) but I don't see the tag on GitHub. Is it possible to add this release metadata to the repo?

**Comment by tom-dalton-fanduel** [comment]
Done :)

**Comment by plantfansam** [comment]
Thanks!!
